# Generated by Django 6.0 on 2026-01-02 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('exam', 'Exam'), ('homework', 'Homework'), ('oral_presentation', 'Oral Presentation'), ('project', 'Project'), ('field_trip', 'Field Trip'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.CharField(blank=True, help_text='e.g., "10:00 AM"', max_length=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('participants', models.TextField(blank=True, help_text='Comma-separated names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, help_text='Legacy: e.g., "22"', max_length=10)),
                ('month', models.CharField(blank=True, help_text='Legacy: e.g., "DEC"', max_length=10)),
                ('time', models.CharField(blank=True, help_text='Legacy: e.g., "10:00 AM • Class A"', max_length=100)),
                ('type', models.CharField(blank=True, help_text='Legacy: e.g., "type-exam"', max_length=50)),
                ('assigned_courses', models.ManyToManyField(blank=True, related_name='events', to='dashboard.course')),
                ('assigned_groups', models.ManyToManyField(blank=True, related_name='events', to='dashboard.group')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
