# Generated by Django 6.0 on 2026-01-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.AddField(
            model_name='session',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', help_text='Day of the week', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.CharField(default='', help_text='e.g., "Room 101"', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='09:00', help_text='End time in 24-hour format (HH:MM)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='Start time in 24-hour format (HH:MM)'),
        ),
    ]
