# Generated by Django 6.0 on 2026-01-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.JSONField(blank=True, default=dict, help_text='{"music": ["K-Pop", "Rock"], "sports": ["Soccer", "Volleyball"]}'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('test', 'Test'), ('presentation', 'Presentation'), ('participation', 'Participation'), ('project', 'Project')], max_length=20)),
                ('title', models.CharField(help_text='Assignment/test name', max_length=200)),
                ('numeric_score', models.FloatField(help_text='Score from 0-20')),
                ('date_recorded', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='dashboard.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['student', 'course'], name='students_gr_student_3cbfed_idx'), models.Index(fields=['date_recorded'], name='students_gr_date_re_f22090_idx')],
            },
        ),
    ]
