# Generated by Django 6.0 on 2026-01-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('students', '0002_student_interests_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('hobbies', 'Hobbies'), ('academic', 'Academic'), ('arts', 'Arts'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='interests_json',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy JSON format: {"music": ["K-Pop"], "sports": ["Soccer"]}'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_tutor',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned as tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Tutor/mentor for this student (can be another student)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('test', 'Test'), ('presentation', 'Presentation'), ('participation', 'Participation'), ('project', 'Project'), ('exam', 'Exam')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance_rate',
            field=models.FloatField(default=100.0, help_text='Current attendance %'),
        ),
        migrations.AlterField(
            model_name='student',
            name='average_grade',
            field=models.FloatField(default=0.0, help_text='Computed average (0-20)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Comma-separated hobbies (legacy)'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.AlterField(
            model_name='student',
            name='social_circle',
            field=models.TextField(blank=True, help_text='Comma-separated student IDs (friends)'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('max_score', models.FloatField(default=20.0)),
                ('grade_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('test', 'Test'), ('presentation', 'Presentation'), ('participation', 'Participation'), ('project', 'Project'), ('exam', 'Exam')], default='homework', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.course')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Optional link to Task model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='students.task'),
        ),
        migrations.CreateModel(
            name='TeacherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('general', 'General Observation'), ('academic', 'Academic Progress'), ('behavior', 'Behavior'), ('leadership', 'Leadership'), ('participation', 'Participation'), ('concern', 'Concern'), ('achievement', 'Achievement')], default='general', max_length=20)),
                ('text', models.TextField(help_text='Observation text')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to parents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='dashboard.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Observation',
                'verbose_name_plural': 'Teacher Observations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Student interests (e.g., Pop Music, Basketball)', related_name='students', to='students.interest'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for this record')),
                ('attendance_percentage', models.FloatField(help_text='Attendance % for this month')),
                ('classes_attended', models.PositiveIntegerField(default=0)),
                ('classes_total', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: course-specific attendance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['student', 'month'], name='students_at_student_fa3243_idx')],
                'unique_together': {('student', 'course', 'month')},
            },
        ),
    ]
