# Generated by Django 6.0 on 2026-01-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='e.g., "PHIL"', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g., "#4A8B6F"', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('K3', 'Kindergarten 3 years'), ('K4', 'Kindergarten 4 years'), ('K5', 'Kindergarten 5 years'), ('1P', '1st Primary'), ('2P', '2nd Primary'), ('3P', '3rd Primary'), ('4P', '4th Primary'), ('5P', '5th Primary'), ('6P', '6th Primary'), ('1HS', 'I High School'), ('2HS', 'II High School'), ('3HS', 'III High School'), ('4HS', 'IV High School'), ('5HS', 'V High School')], help_text='Grade level for this course', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='grading_systems',
            field=models.JSONField(blank=True, default=list, help_text='List of grading systems, e.g., ["numeric", "gamified"]'),
        ),
        migrations.AddField(
            model_name='course',
            name='section_group',
            field=models.CharField(blank=True, help_text='e.g., "IIIA"', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Upload syllabus PDF', null=True, upload_to='syllabi/'),
        ),
    ]
