# Generated by Django 6.0 on 2026-01-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_course_abbreviation_course_color_course_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload course cover image', null=True, upload_to='course_images/'),
        ),
    ]
