# Generated by Django 6.0 on 2026-01-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, help_text='Unique code for student enrollment', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, help_text='e.g., "Room 101"', max_length=50),
        ),
    ]
