# Generated by Django 6.0 on 2026-01-02 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, help_text='Learning objectives for this lesson')),
                ('content', models.TextField(blank=True, help_text='Main lesson content and activities')),
                ('materials', models.TextField(blank=True, help_text='Required materials and resources')),
                ('homework', models.TextField(blank=True, help_text='Homework assignments')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='dashboard.course')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
    ]
